apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-config
  namespace: portfolio
data:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/portfolio
  AWS_ENDPOINT_URL: http://localstack:4566
  AWS_REGION: us-east-1
  S3_BUCKET: portfolio-exports
  ENV: prod
